import requests
from faker import Faker
from validate_docbr import CPF
import random
from datetime import datetime, timedelta

# Configuration
API_URL = "http://localhost:8000/coletas/"
NUM_RECORDS = 50
fake = Faker('pt_BR')
cpf_generator = CPF()

# Data lists
CIDADES = ["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Curitiba", "Porto Alegre"]
TIPOS_COMBUSTIVEL = ["Gasolina", "Etanol", "Diesel"]
TIPOS_VEICULO = ["Caminhão", "Carro", "Moto", "Van"]

def generate_fake_coleta():
    """Generates a single fake fuel collection record."""
    
    # Generate a valid CPF
    cpf = cpf_generator.generate()
    
    # Generate a random date in the last 30 days
    start_date = datetime.now() - timedelta(days=30)
    data_coleta = fake.date_time_between(start_date=start_date, end_date="now")
    
    return {
        "tipo_combustivel": random.choice(TIPOS_COMBUSTIVEL),
        "volume_litros": round(random.uniform(10.0, 150.0), 2),
        "preco_venda": round(random.uniform(4.5, 7.5), 2),
        "cpf_motorista": cpf,
        "cidade": random.choice(CIDADES),
        "tipo_veiculo": random.choice(TIPOS_VEICULO),
        # data_coleta is not sent as it's auto-generated by the backend
    }

def seed_data():
    """Sends fake data to the API."""
    print(f"Starting data seeding: sending {NUM_RECORDS} records to {API_URL}")
    
    for i in range(NUM_RECORDS):
        data = generate_fake_coleta()
        try:
            response = requests.post(API_URL, json=data)
            response.raise_for_status() # Raise an exception for bad status codes (4xx or 5xx)
            print(f"Record {i+1}/{NUM_RECORDS} successfully created. Status: {response.status_code}")
        except requests.exceptions.RequestException as e:
            print(f"Error sending record {i+1}/{NUM_RECORDS}: {e}")
            print(f"Data sent: {data}")
            if response is not None:
                print(f"Response content: {response.text}")
            break # Stop on first error

if __name__ == "__main__":
    # Note: This script assumes the backend is running and accessible at localhost:8000
    seed_data()
